### ISSUE TITLE
Official client now on packagist

### ISSUE THREAD

**Issue by jackmahoney** [rvalitov/mailslurp-php#3]
Hi @rvalitov thanks so much for this. You can now use the official package on packagist

https://packagist.org/packages/mailslurp/swagger-sdk-php

**Comment by rvalitov** [comment]
Thank you for the info. But the URL is wrong, that repository does not work. The correct working official repository is https://packagist.org/packages/mailslurp/mailslurp-client-php

**Comment by jackmahoney** [comment]
Ah, thank you, must have changed since original post.
